# -*- coding: utf-8 -*-
"""Salinan dari Range-indexing-slicing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sS2BtSK4d9zmLFq2o_YYnhHrdnRr5ocd
"""

numbers = range(10) # start 0; stop 10; step 1
print(numbers)
print(list(numbers))

numbers = range(1,12) # start 1; stop 11; step 1
print(list(numbers))

numbers = range(5,21,5) # start 5; stop 20; step 5
print(list(numbers))

# Indexing

num = list(range(4,21))
print(num)

num7 = num[3]
print(num7)

print(num[5])

print(num[2])

print (num[-1])

# Sciling
numbers = list (range(1,101))
print(numbers)

print(numbers[:6]) # index 0 sampai index (6-1)

print(numbers[0:6]) # index 0 sampai index (6-1)

print (numbers[3:9]) # index 3 sampau index (9-1)

print (numbers[0:11:2]) # index 0 sampai index 11 dengan interval 2

print(numbers[91:]) #index 91 sampai index terakhir

# create a variable called 'numbers'
# creat a list of numbers 1 - 250 using list(range())
numbers = list(range(1,251))
print(numbers)
# print a number from index 15
print(numbers[15])


# print an eight number from the back
# clue : negative indexing
print(numbers[-8:])

# print a group of numbers, start from 55 until 67
print(numbers[54:67])

# print a group of even numbers, starts from 70 until 240
# clue : use step parameter
print(numbers[69:240:2])